#!/bin/bash
#
#  vbshortcuts
#  VirtualBox shortcuts to an easy VM management, feel free to dix and imporove.
#
#  use: "$ source vbshortcuts" or "$ . vbshortcuts"
#
#  (c)2015 - Giovanni Nunes <giovanni.nunes@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
VBMAN=$( which vboxmanage | which VBoxManage )
# echo $VBMAN --> /usr/bin/VBoxManage

function vbSnapshot(){
    ${VBMAN} snapshot ${2} ${1} ${3}
}


function vbControlVM(){
    ${VBMAN} controlvm ${2} ${1}
}


alias vblist="${VBMAN} list vms"
alias vbwho="${VBMAN} list runningvms"
alias vbinfo="${VBMAN} showvminfo"
alias vbstart="${VBMAN} startvm --type headless"
alias vbacpi="vbControlVM acpipowerbutton"
alias vbstop="vbControlVM poweroff"
alias vbrestart="vbControlVM reset"
alias vbsave="vbControlVM savestate"
alias vbpause="vbControlVM pause"
alias vbresume="vbControlVM resume"
alias vbsnapshot="IFS='%%' ; vbSnapshot take"
alias vbsnaplist="vbSnapshot list"
alias vbsnapdel="IFS='%%' ; vbSnapshot delete" 
alias vbsnaprestore="IFS='%%' ; vbSnapshot restore"

# MSX Rulez!

# Usando a tecla «TAB» à seu favor. Use, por exemplo "vbrestart $_«TAB»" e serão exibidas as opções "_DEB", "_SUSE" e "_CENT".

export _DEB="Debian10_x64.0"
export _SUSE="Opensuse15_x64.0"
export _CENT="CentOS7_x64.0"

# Fonte: Disponível em "https://giovannireisnunes.wordpress.com/2015/10/30/virtualbox-na-linha-de-comando/". Acesso em: 19/02/2020.
