---
- name: Install and Configure {{ web_service | default('httpd') }}
  hosts: "{{ nodes }}"
  become: yes
  tasks:
    - name: Install {{ web_package }} and {{ firewall_package }}
      yum:
        name:
          - "{{ web_package }}"
          - "{{ firewall_package }}" 
        state: latest
    
    - name: Enable and Start {{ web_service }}
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started

    - name: Enable and Start {{ firewall_service }}
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: Open Firewall Ports for {{ web_service }}
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Copy HTML Content
      copy:
        content: "Welcome to your Website <br>(This is deployed using Ansible)"
        dest: /var/www/html/index.html

# Here starts a new play. Pay attention at level of indentation!
- name: Test and Verify Webservers
  hosts: localhost
  become: no
  tasks:
    - name: Connect To Webserver
      uri:
        url: http://node2
        # the status_code should be "200" if no, returns error.
        status_code: 200
...
