- hosts: all
  vars:
    hello:
      - Wold
      - Asia
      - South America
      - North America
      - Artic
      - Antartic
      - Oceania
      - Europe
      - Africa
  tasks:
    - name: Ansible List Variable Example
      debug:
        msg: "{{ hello[2] }}"
