- hosts: all
  vars:
    hello: [Asia, Americas, Artic, Antartic, Oceania, Europe, Africa]
  tasks:
  - name: Ansible List Variable Example
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ hello }}"
