---
# tasks file for myweb
- name: Install httpd and firewalld
  yum:
    name:
      - "{{ web_package }}" # This was defined on 'roles/defaults/main.yml'
      - "{{ firewall_package }}" # This was defined on 'roles/defaults/main.yml'
    state: latest
  notify:
    - Restart webservice
    - Restart firewalld

- name: Firewalld permitt httpd service
  firewalld:
    # service: http
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: yes

  notify:
    - Restart webservice
    - Restart firewalld

- name: Test html page is installed
  copy:
    content: "Welcome to the example.com intranet!\n"
    dest: /var/www/html/index.html
...
