ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |vm_machine|
  # Customizations for better performance:  
  # General 1/4 - Basic:
  #vm_machine.customize ["modifyvm", :id, "--name", "ansiblecontroller"]
  # General 2/4 - Advanced:
  vm_machine.customize ["modifyvm", :id, "--clipboard", "disabled"]
  vm_machine.customize ["modifyvm", :id, "--draganddrop", "disabled"]
  # System 1/3 - Motherboard:
  vm_machine.customize ["modifyvm", :id, "--memory", "512"]
  vm_machine.customize ["modifyvm", :id, "--pagefusion", "on"]
  vm_machine.customize ["modifyvm", :id, "--boot1", "disk"]
  vm_machine.customize ["modifyvm", :id, "--chipset", "piix3"]
  vm_machine.customize ["modifyvm", :id, "--mouse", "ps2"]
  vm_machine.customize ["modifyvm", :id, "--ioapic", "on"]
  vm_machine.customize ["modifyvm", :id, "--rtcuseutc", "on"]
  # System 2/3 - Processor:
  vm_machine.customize ["modifyvm", :id, "--cpus", "2"]
  vm_machine.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  vm_machine.customize ["modifyvm", :id, "--pae", "on"]
  # System 3/3 - Acceleration:
  vm_machine.customize ["modifyvm", :id, "--paravirtprovider", "default"]
  vm_machine.customize ["modifyvm", :id, "--nestedpaging", "on"]
  # Display 1/3 - Screen:
  vm_machine.customize ["modifyvm", :id, "--vram", "8"]
  vm_machine.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  # Audio 1/1 - Audio:
  vm_machine.customize ["modifyvm", :id, "--usb", "off"]
  vm_machine.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  # Configure the controller node:
  config.vm.define "controller" do |guest_ansible|
    guest_ansible.vm.box = "centos/7"
    guest_ansible.vm.box_version = "2004.01"
    guest_ansible.vm.box_check_update = "true"
    guest_ansible.vm.hostname = "ansiblecontroller"
    guest_ansible.vm.network "public_network", bridge: "enp7s0", ip: "192.168.0.190"
    guest_ansible.vm.post_up_message = "Infra As A Code - Vagrant in Action!"
  end


  # Configure the target nodes:
  # For multiple machines:
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.box_version = "2004.01"
      node.vm.box_check_update = "true"
      node.vm.hostname = "ansibletarget#{i}"
      node.vm.network "public_network", bridge: "enp7s0", ip: "192.168.0.19#{i}"
      node.vm.post_up_message = "Infra As A Code - Vagrant in Action!"
    end
  end
end
