# This file: ./loop_with_list2.yml
---
- name: Loop & Task Control
  hosts: nodes
  become: true
  vars:
    userlist:
      - leela
      - fry
      - bender
      - hermes
      - barbados
      - flexo
      - hubert
      - zoidberg
      - zapp
  tasks:
    - name: Create Users of Express Planet
      user:
        name: "{{ item }}"
      with_list: "{{ userlist }}"
...
