# This file: ./secrets.yaml
---
- name: Using Secrets in Playbook
  hosts: nodes
  become: true
  vars_files:
    # This is the encrypted file that contains username and password.
    - user-passwd.yaml
    # This below is a BAD IDEA! We're define use and password in plaintext in unencrypt file :(
    # username: bender
    # passwd: vesenaomeenchenao
  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ passwd | password_hash('sha256') }}"
...
