# This file: ./tasks_ctrl_sample.yaml
---
- name: Loop & Task Control
  hosts: nodes
  become: true
  tasks:
    - name: Install Packages
      yum:
        name:
          - httpd
          - firewalld
        state: present

    - name: Enable httpd Service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Enable firewalld Service
      service:
        name: firewalld
        state: started
        enabled: true
...
